services:
  poetry-api:
    image: palemoky/chinese-poetry-api:latest
    container_name: poetry-api
    restart: unless-stopped
    ports:
      - "${PORT:-1279}:${PORT:-1279}"
    env_file:
      - .env
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./data:/app/data
