services:
  poetry-api:
    image: palemoky/chinese-poetry-api:latest
    container_name: chinese-poetry-api
    ports:
      - "${PORT:-1566}:${PORT:-1566}"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped
